apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-oebs-api-proxy
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
  port: 8080
  secureLogs:
    enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 500m
      memory: 3000Mi
    requests:
      cpu: 50m
      memory: 600Mi
  envFrom:
    - secret: hm-oebs-api-proxy-secret
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/dev/creds/oebst1-dhotuser
        mountPath: /secrets/oebst1/credentials
      - kvPath: oracle/data/dev/config/oebst1
        mountPath: /secrets/oebst1/config
      - kvPath: oracle/data/dev/creds/oebsq1-dhotuser
        mountPath: /secrets/oebsq1/credentials
      - kvPath: oracle/data/dev/config/oebsq1
        mountPath: /secrets/oebsq1/config
  ingresses:
    - https://hm-oebs-api-proxy.dev-fss-pub.nais.io
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          # Saksbehandling:
          - id: "b9340050-ccb5-4de7-9d96-0fb2d9fb38eb" # 0000-GA-hotsak-brukere
          - id: "1aa0caef-04cc-4446-8ed3-bbb78d59681c" # 0000-GA-brilleadmin-brukere
  tokenx:
    enabled: true
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-dinehjelpemidler
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-forslagsmotor-tilbehoer
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-saksberiker
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-oebs-sink
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-saksbehandling
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-bestillingsordning-river
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-bestillingsordning-sjekker
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-soknad-api
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-kommune-api
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-delbestilling-api
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-roller
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-soknadsbehandling
          namespace: teamdigihot
          cluster: dev-gcp
    outbound:
      rules:
        - application: hm-grunndata-search
      external:
        - host: hm-grunndata-api.intern.dev.nav.no
