apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-oebs-api-proxy
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 500m
      memory: 3000Mi
    requests:
      cpu: 50m
      memory: 600Mi
  vault:
    enabled: true
    paths:
      # Q1
      - kvPath: secret/team-oebs/digihot/dev/Q1/apps-user
        mountPath: /secrets/q1/oebs/apps-user
      - kvPath: secret/team-oebs/digihot/dev/Q1/db-user
        mountPath: /secrets/q1/oebs/db-user
      # Q2
      - kvPath: secret/team-oebs/digihot/dev/Q2/apps-user
        mountPath: /secrets/q2/oebs/apps-user
      - kvPath: secret/team-oebs/digihot/dev/Q2/db-user
        mountPath: /secrets/q2/oebs/db-user
      # T1
      - kvPath: secret/team-oebs/digihot/dev/T1/apps-user
        mountPath: /secrets/t1/oebs/apps-user
      - kvPath: secret/team-oebs/digihot/dev/T1/db-user
        mountPath: /secrets/t1/oebs/db-user
      # U1
      - kvPath: secret/team-oebs/digihot/dev/U1/apps-user
        mountPath: /secrets/u1/oebs/apps-user
      - kvPath: secret/team-oebs/digihot/dev/U1/db-user
        mountPath: /secrets/u1/oebs/db-user
  ingresses:
    - https://hm-oebs-api-proxy.dev-fss-pub.nais.io
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          # Saksbehandling:
          - id: "b9340050-ccb5-4de7-9d96-0fb2d9fb38eb" # 0000-GA-hotsak-brukere
          - id: "1aa0caef-04cc-4446-8ed3-bbb78d59681c" # 0000-GA-brilleadmin-brukere
  tokenx:
    enabled: true
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-grunndata-alternativprodukter
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-dinehjelpemidler
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-forslagsmotor-tilbehoer
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-saksfordeling
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-oebs-sink
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-saksbehandling
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-bestillingsordning-river
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-bestillingsordning-sjekker
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-soknad-api
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-kommune-api
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-delbestilling-api
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-roller
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-soknadsbehandling
          namespace: teamdigihot
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: tokenx-token-generator
          namespace: nais
          cluster: dev-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: hm-grunndata-search.intern.dev.nav.no
        - host: norg2.dev.intern.nav.no
  env:
    - name: OEBS_BRUKER_ID
      value: "81400"
    - name: OEBS_MILJO
      value: "q1"
    - name: GRUNNDATA_API_URL
      value: https://hm-grunndata-search.intern.dev.nav.no
    - name: NORG_API_URL
      value: https://norg2.dev.intern.nav.no/norg2/api/v1
