apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-oebs-api-proxy
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
  port: 8080
  secureLogs:
    enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  envFrom:
    - secret: hm-oebs-api-proxy-secret
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/prod/creds/oebsp-dhotuser
        mountPath: /secrets/oebsp/credentials
      - kvPath: oracle/data/prod/config/oebsp
        mountPath: /secrets/oebsp/config
  ingresses:
    - https://hm-oebs-api-proxy.prod-fss-pub.nais.io
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-dinehjelpemidler
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-forslagsmotor-tilbehoer
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-saksberiker
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-oebs-sink
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-saksbehandling
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-bestillingsordning-river
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-bestillingsordning-sjekker
          namespace: teamdigihot
          cluster: prod-gcp
    outbound:
      external:
        - host: hm-grunndata-api.intern.nav.no
        - host: hm-oebs-api-proxy.prod-fss-pub.nais.io