apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-oebs-api-proxy
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  port: 8080
  secureLogs:
    enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/dev/creds/oebst1-dhotuser
        mountPath: /secrets/oebst1/credentials
      - kvPath: oracle/data/dev/config/oebst1
        mountPath: /secrets/oebst1/config
      - kvPath: oracle/data/dev/creds/oebsq1-dhotuser
        mountPath: /secrets/oebsq1/credentials
      - kvPath: oracle/data/dev/config/oebsq1
        mountPath: /secrets/oebsq1/config
  ingresses:
    - https://hm-oebs-api-proxy.dev-fss-pub.nais.io
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-dinehjelpemidler
          namespace: teamdigihot
          cluster: dev-gcp
    outbound:
      external:
        - host: hm-produktinfo-api-poc.nais.preprod.local/api