apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-oebs-api-proxy
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 500m
      memory: 3000Mi
    requests:
      cpu: 50m
      memory: 600Mi
  envFrom:
    - secret: hm-oebs-api-proxy-secret
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/prod/creds/oebsp-dhotuser
        mountPath: /secrets/oebsp/credentials
      - kvPath: oracle/data/prod/config/oebsp
        mountPath: /secrets/oebsp/config
  ingresses:
    - https://hm-oebs-api-proxy.prod-fss-pub.nais.io
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          # Saksbehandling:
          - id: "2f632b40-4730-4692-9c7c-fb744e2d33e1" # teamdigihot
          - id: "88956569-f23d-455c-ace4-001b56e94602" # 0000-GA-hotsak-brukere
          - id: "d6f989d6-59a9-4d18-9cd1-f1372dcccfe5" # 0000-GA-brilleadmin-brukere
  tokenx:
    enabled: true
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-grunndata-alternativprodukter
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-dinehjelpemidler
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-forslagsmotor-tilbehoer
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-saksfordeling
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-oebs-sink
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-saksbehandling
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-bestillingsordning-river
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-bestillingsordning-sjekker
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-soknad-api
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-kommune-api
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-delbestilling-api
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-roller
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-soknadsbehandling
          namespace: teamdigihot
          cluster: prod-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: hm-grunndata-search.intern.nav.no
        - host: hm-oebs-api-proxy.prod-fss-pub.nais.io
  env:
    - name: OEBS_BRUKER_ID
      value: "81760"
    - name: OEBS_API_URL
      value: https://oebs.adeo.no/webservices/rest/opprettordre/digihotordreontinfo/
    - name: OEBS_DB
      value: oebsp
    - name: GRUNNDATA_API_URL
      value: https://hm-grunndata-search.intern.nav.no
    - name: NORG_API_URL
      value: https://norg2.intern.nav.no/norg2/api/v1
