CREATE SCHEMA IF NOT EXISTS apps;

-- Bruker tabell for å simulere view i OEBS
CREATE TABLE IF NOT EXISTS apps.XXRTV_DIGIHOT_HJM_UTLAN_FNR_V
(
    FOREKOMST_NUMMER           VARCHAR2(30),
    ORDRE_NUMMER               NUMBER,
    ANTALL                     NUMBER,
    KATEGORI3_NUMMER           VARCHAR2(163),
    KATEGORI3_BESKRIVELSE      VARCHAR2(240),
    ARTIKKELSTATUS             VARCHAR2(50),
    UTLÅNS_TYPE                VARCHAR2(240),
    UTLÅNS_DATO                DATE,
    OPPRETTELSESDATO           DATE,
    INNLEVERINGSDATO           DATE,
    OPPDATERT_INNLEVERINGSDATO DATE,
    SERIE_NUMMER               VARCHAR2(30),
    ARTIKKEL_BESKRIVELSE       VARCHAR2(240),
    ARTIKKELNUMMER             VARCHAR2(40),
    ENHET                      VARCHAR2(3),
    BRUKER_NUMMER              VARCHAR2(30),
    FNR                        VARCHAR2(30),
    EGEN_ANSATT                VARCHAR2(150),
    NAVN                       VARCHAR2(360),
    INSTALLASJONS_ADDRESSE     VARCHAR2(722),
    INSTALLASJONS_KOMMUNE      VARCHAR2(60),
    INSTALLASJONS_POSTNUMMER   VARCHAR2(60),
    INSTALLASJONS_BY           VARCHAR2(60),
    BOSTEDS_ADDRESSE           VARCHAR2(722),
    BOSTEDS_KOMMUNE            VARCHAR2(60),
    BOSTEDS_POSTNUMMER         VARCHAR2(60),
    BOSTEDS_BY                 VARCHAR2(60)
);

INSERT INTO apps.XXRTV_DIGIHOT_HJM_UTLAN_FNR_V(FOREKOMST_NUMMER, ORDRE_NUMMER, ANTALL, KATEGORI3_NUMMER,
                                               KATEGORI3_BESKRIVELSE, ARTIKKELSTATUS, UTLÅNS_TYPE, UTLÅNS_DATO,
                                               OPPRETTELSESDATO, INNLEVERINGSDATO, OPPDATERT_INNLEVERINGSDATO,
                                               SERIE_NUMMER, ARTIKKEL_BESKRIVELSE, ARTIKKELNUMMER, ENHET, BRUKER_NUMMER,
                                               FNR, EGEN_ANSATT, NAVN, INSTALLASJONS_ADDRESSE, INSTALLASJONS_KOMMUNE,
                                               INSTALLASJONS_POSTNUMMER, INSTALLASJONS_BY, BOSTEDS_ADDRESSE,
                                               BOSTEDS_KOMMUNE, BOSTEDS_POSTNUMMER, BOSTEDS_BY)
VALUES ('', 1, 1, '', '', '', '', '2020-02-01', '2020-01-01', '2020-10-01', '2020-11-01', '', '', '', '', '',
        '12345678910', '', '', '', '', '0000', '', '', '', '0000', '');

-- Bruker tabell for å simulere view i OEBS
CREATE TABLE IF NOT EXISTS apps.XXRTV_DIGIHOT_OEBS_ADR_FNR_V
(
    BRUKER_NUMMER        VARCHAR2(30),
    FNR                  VARCHAR2(30),
    EGEN_ANSATT          VARCHAR2(150),
    NAVN                 VARCHAR2(360),
    BOSTEDS_ADDRESSE     VARCHAR2(722),
    BOSTEDS_KOMMUNE      VARCHAR2(60),
    BOSTEDS_POSTNUMMER   VARCHAR2(60),
    BOSTEDS_BY           VARCHAR2(60),
    BYDEL                VARCHAR2(60),
    LEVERINGS_ADDRESSE   VARCHAR2(722),
    LEVERINGS_KOMMUNE    VARCHAR2(60),
    LEVERINGS_POSTNUMMER VARCHAR2(60),
    LEVERINGS_BY         VARCHAR2(60),
    PRIMAER_ADR          VARCHAR2(1),
    STATUS_BRUKERNR      VARCHAR2(1),
    STATUS_FNR           VARCHAR2(1),
    STATUS_ADR_P_STED    VARCHAR2(1),
    STATUS_ADR_C_STED    VARCHAR2(1),
    STATUS_ADR_BRU       VARCHAR2(1)
);

INSERT INTO apps.XXRTV_DIGIHOT_OEBS_ADR_FNR_V (BRUKER_NUMMER, FNR, EGEN_ANSATT, NAVN, BOSTEDS_ADDRESSE, BOSTEDS_KOMMUNE,
                                               BOSTEDS_POSTNUMMER, BOSTEDS_BY, BYDEL, LEVERINGS_ADDRESSE,
                                               LEVERINGS_KOMMUNE, LEVERINGS_POSTNUMMER, LEVERINGS_BY, PRIMAER_ADR,
                                               STATUS_BRUKERNR, STATUS_FNR, STATUS_ADR_P_STED, STATUS_ADR_C_STED,
                                               STATUS_ADR_BRU)
VALUES ('1', '12345678910', '', '', '', '', '0000', '', '', 'test', '', '0000', '', '0', '', '', '', '', '');

-- Bruker tabell for å simulere view i OEBS
CREATE TABLE IF NOT EXISTS apps.XXRTV_DIGIHOT_OEBS_ART_BESKR_V
(
    ARTIKKEL               VARCHAR2(40),
    ARTIKKEL_BESKRIVELSE_B VARCHAR2(240),
    ARTIKKEL_BESKRIVELSE   VARCHAR2(240),
    BRUKERARTIKKELTYPE     VARCHAR2(80),
    LANGUAGE               VARCHAR2(4),
    LISTEPRIS_ENHET        NUMBER,
    ORG_ID                 NUMBER
);

INSERT INTO apps.XXRTV_DIGIHOT_OEBS_ART_BESKR_V(ARTIKKEL, ARTIKKEL_BESKRIVELSE_B, ARTIKKEL_BESKRIVELSE,
                                                BRUKERARTIKKELTYPE, LANGUAGE, LISTEPRIS_ENHET, ORG_ID)
VALUES ('1', 'test', 'test', 'test', '', 0, 0);

-- Bruker tabell for å simulere view i OEBS
CREATE TABLE IF NOT EXISTS apps.XXRTV_DIGIHOT_OEBS_BRUKERP_V
(
    FNR             VARCHAR2(30),
    KONTRAKT_NUMMER VARCHAR2(150),
    SJEKK_NAVN      VARCHAR2(150),
    START_DATE      DATE,
    END_DATE        DATE
);

INSERT INTO apps.XXRTV_DIGIHOT_OEBS_BRUKERP_V(FNR, KONTRAKT_NUMMER, SJEKK_NAVN, START_DATE, END_DATE)
VALUES ('12345678910', 'test', 'test', '2020-01-01', NULL);

-- Bruker tabell for å simulere view i OEBS
CREATE TABLE IF NOT EXISTS apps.XXRTV_DIGIHOT_UTVID_ART_V
(
    ORGANISASJONS_ID     NUMBER(15),
    ORGANISASJONS_NAVN   VARCHAR2(240),
    ARTIKKELNUMMER       VARCHAR2(40),
    ARTIKKELID           NUMBER,
    ARTIKKEL_BESKRIVELSE VARCHAR2(240),
    KATEGORI_NUMMER      VARCHAR2(4000),
    KATEGORI_BESKRIVELSE VARCHAR2(4000),
    FYSISK               NUMBER,
    TILGJENGELIGATT      NUMBER,
    TILGJENGELIGROO      NUMBER,
    TILGJENGELIG         NUMBER,
    BEHOVSMELDT          NUMBER,
    RESERVERT            NUMBER,
    RESTORDRE            NUMBER,
    BESTILLINGER         NUMBER,
    ANMODNING            NUMBER,
    INTANMODNING         NUMBER,
    FORSYNING            NUMBER,
    SORTIMENT            VARCHAR2(4000),
    LAGERVARE            VARCHAR2(4000),
    MINMAX               VARCHAR2(4000)
);

INSERT INTO apps.XXRTV_DIGIHOT_UTVID_ART_V(ORGANISASJONS_ID, ORGANISASJONS_NAVN, ARTIKKELNUMMER, ARTIKKELID,
                                           ARTIKKEL_BESKRIVELSE, KATEGORI_NUMMER, KATEGORI_BESKRIVELSE, FYSISK,
                                           TILGJENGELIGATT, TILGJENGELIGROO, TILGJENGELIG, BEHOVSMELDT, RESERVERT,
                                           RESTORDRE, BESTILLINGER, ANMODNING, INTANMODNING, FORSYNING, SORTIMENT,
                                           LAGERVARE, MINMAX)
VALUES (123456789, 'test', '123456', 1, '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '');

CREATE SEQUENCE IF NOT EXISTS apps.XXRTV_CS_DIGIHOT_SF_OPPRETT_S;

-- Bruker tabell for å simulere view i OEBS
CREATE TABLE IF NOT EXISTS apps.XXRTV_CS_DIGIHOT_SF_OPPRETT
(
    ID                   NUMBER DEFAULT apps.XXRTV_CS_DIGIHOT_SF_OPPRETT_S.nextval,
    FNR                  VARCHAR2(30),
    NAVN                 VARCHAR2(360),
    STONADSKLASS         VARCHAR2(255),
    SAKSTYPE             VARCHAR2(255),
    RESULTAT             VARCHAR2(255),
    SFDATO               DATE,
    REFERANSENUMMER      VARCHAR2(255),
    KILDE                VARCHAR2(255),
    PROCESSED            VARCHAR2(255),
    LAST_UPDATE_DATE     DATE,
    LAST_UPDATED_BY      VARCHAR2(255),
    CREATION_DATE        DATE,
    CREATED_BY           VARCHAR2(255),
    JOB_ID               VARCHAR2(255),
    SAKSBLOKK            VARCHAR2(255),
    BESKRIVELSE          VARCHAR2(255),
    JSON_ARTIKKELINFO_IN CLOB,

    PRIMARY KEY (ID)
);
